=== Conceptual model conventions (UML)

[[sec:cmc-r1]]
==== UML as a single source of truth
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* UML as a single source of truth

|{set:cellbgcolor: #f5f8fc}
*Acronym*: CMC-R1

|*Statement*

The UML conceptual model should be used as the single source of truth.
|===

*Description*

By applying this principle, we can achieve consistency among all derived artefacts.

This implies:

* Standard representation of the UML such as XMI or EAP database
* Existence of a well-defined set of rules and conventions to transform UML model into other artefacts, which can be executed,
as much as possible automatically, by a dedicated software tool or toolchain [xref:gc-conceptual-model-conventions.adoc#sec:cmc-r2[CMC-R2]]

It is recommended that recent versions of the UML (v2.5+) and XMI (v2.5+) specifications are used [xref:references.adoc#ref:27[27]].


[[sec:cmc-r2]]
==== Fixed UML interpretation

|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Fixed UML interpretation

|{set:cellbgcolor: #f5f8fc}
*Acronym*: CMC-R2

|*Statement:*

Using UML as a graphical language to encode a data specification according to the reuse guidelines requires defining a set
of pre-established conventions on the UML notation to reach a fixed interpretation.

|===

*Description:*

The interpretation of UML as a logical structure, including OWL, was and still is an active research topic. But even the
OMG Ontology Definition Metamodel [xref:references.adoc#ref:28[28]] does not address the notion of reuse. The goal of using
UML is to provide for the SEMIC semantic data specifications a standard graphical notation which many are familiar with.
Therefore, the graphical notation should facilitate the understanding of the data specification. The UML notation should
match the semantics that are to be expressed in the data specification (the ontology, data shapes and human-readable documentation).

The UML is the single source of truth [xref:gc-conceptual-model-conventions.adoc#sec:cmc-r1[CMC-R1]]. Using the conventions
and associated interpretation expressed in this rule, other artefacts are derived from the UML. The benefit of defining such
a precise set of mapping rules is that it allows for:

* Implementing tools to transform UML into derivative artefacts, thus enabling UML as the single source of truth.
* Implementing tools for formal checking against the established conventions (interpretation), thus enforcing correctness,
conformance and consistency.

These rules will increase the coherency of the UML diagrams across projects and organisations.

Within SEMIC, the interpretation is implemented by the SEMIC toolchain [xref:references.adoc#ref:15[15]]. [??? - should we add a ref?]

The table below provides recommended interpretations of UML elements in OWL and SHACL.
These interpretations can be considered high-level mapping rules implementable into transformation tools that generate
OWL ontology and, respectively, SHACL constraints from the UML conceptual model.

[%autowidth]
|===
|*UML model element*|*OWL ontology element*|*SHACL data shape element*
|*Class*|OWL Class|SHACL Node Shape
|*Abstract class*||SHACL Node Shape with a SPARQL constraint that selects all instances of this class
|*Attribute*|OWL datatype or object property, based on their type.|Property constraint, within the SHACL Node Shape corresponding
to the source UML class (but the constraints are mentioned below on type and multiplicity)
|*Attribute type*||Property constraint, within the SHACL Node Shape corresponding to the UML class, indicating the range
class or datatype.
|*Attribute multiplicity*||Property constraint(s), within the SHACL Node
|*Association (target/source role names)*|Object property declaration axiom for the target (or source, or both) end of
the association.|
|*Association source*|Optional domain declaration (data shape constraints shall be preferred).|Property constraint, within
the SHACL Node Shape corresponding to the source UML class (but the constraints are mentioned below on target and multiplicity)
|*Association target*|Optional property range declaration (data shape constraints shall be preferred).|Property constraint,
within the SHACL Node Shape corresponding to the source UML class, indicating the range class
|*Association multiplicity*||Property constraints, within the SHACL Node Shape corresponding to the source UML class, indicating
the minimum and/or maximum or exact cardinality (similar to Attribute multiplicity).
|*Association symmetry*||SPARQL constraint, within the SHACL Node Shape, corresponding to the UML constraint, within the class,
which selects instances connected by the object property in a reciprocal manner.
|*Association inverse (for bidirectional associations only)*|Two object property declaration axioms, one for the target and
the second for the source end of the association, and a declaration that the two properties stand in an inverse relationship
to one another.|
|*Dependency*|Object property declaration axiom for the target end of the association.|
|*Dependency source*||Property constraint, within the SHACL Node Shape corresponding to the source UML class (but the constraints
are mentioned below on target and multiplicity)
|*Dependency target*||Property constraints, within the SHACL Node Shape corresponding to the source UML class, indicating
(a) the range class is skos:Concept and (b) the value is skos:inScheme the target name (expected an enumeration).
|*Dependency multiplicity*||Property constraints within the SHACL
|*Class generalisation*|Subclass axiom between the classes corresponding to the UML classes. |
|*Property generalisation*|Sub-property axiom for the generalisation between UML associations and dependencies.|
|===

*Examples*

The UML interpretation applied by the SEMIC toolchain is described in [ref]. To assist the editor while data modelling to
choose the best representation, a test suite is available covering all modelling patterns.

The SEMIC toolchain shares the same interpretation as the OSLO toolchain [xref:references.adoc#ref:17[17]].

In the context of eProcurement ontology, a toolchain has been developed to transform and validate UML models. Such tools
are based on two documents: UML convention specifications [xref:references.adoc#ref:29[29]] and UML transformation specifications
[xref:references.adoc#ref:30[30]].


[[sec:cmc-r3]]
==== On element names and URIs


[[sec:cmc-r4]]
==== Case sensitivity and charset


[[sec:cmc-r5]]
==== Namespaces and prefixes in element names


[[sec:cmc-r6]]
==== Rich annotations through tags


[[sec:cmc-r7]]
==== Explicit depiction of external dependencies


[[sec:cmc-r8]]
==== Class inheritance


[[sec:cmc-r9]]
==== Abstract classes


[[sec:cmc-r10]]
==== Attribute specifications


[[sec:cmc-r11]]
==== Multiplicity of attributes and connectors


[[sec:cmc-r12]]
==== Connector specification


[[sec:cmc-r13]]
==== All elements are "public"


[[sec:cmc-r14]]
==== Controlled lists as enumerations


[[sec:cmc-r15]]
==== Partition the model into packages


[[sec:cmc-r16]]
==== Diagram readability

