[[sec:requirements]]
== Requirements

This section elaborates on the general design criteria along with
requirements the Core Vocabularies should fulfil.

[[sec:functional-requirements]]
=== Functional requirements

NOTE: Do we have functional requirements the CV shall support?

* _Interconnection of public procurement systems_: to support increased
interoperability across procurement systems.
** Increase cross-domain interoperability among Member States
** Introduce automated classification systems in public procurement
systems

[[sec:non-functional-requirements]]
=== Non-functional requirements

NOTE: Do we have non-functional requirements the CV shall support?

This section provides the characteristics, qualities and general aspects
that the Core Vocabularies should satisfy.

* The practices, technologies and standards must be aligned with the
European Directive on open data and the reuse of public sector
information , the single digital gateway regulation .

* The terminology used in the ontology should be reused from established
vocabularies and domain ontologies as long as their meaning fits
into the description of the Core Vocabulary.

* The concept and relation labels must allow for multilingual content,
covering at least the official European Languages .

* The content of the formal model must be consistent with the predefined set
of UML conceptual model conventions .

* The URI identifiers must follow a strict URI policy defined in
Section #sec:uri-policy[[sec:uri-policy]].

* The Core Vocabularies design must commit long term URI persistence.

* The Core Vocabularies, and the related artefacts, must be layered in order to
support different degrees of ontological commitment and levels formal
specification stacked on each other (see Section
#sec:layers-components[[sec:layers-components]]).

* The Core Vocabularies, and the related artefacts, must be sliced in order to
support a modular organisation of the domain in terms of self-contained
or semi-dependent modules (see Section
#sec:layers-components[[sec:layers-components]]).

NOTE: * The formal model, and the related artefacts, must be generated from
the UML conceptual model, serving as the single source of
truth, through a set of predefined transformation rules .


[[sec:design-criteria]]
=== General design criteria

NOTE: This section refers to a formal ontology. Do we need it, and if so, how shall we relate CV to ontologies?

For the purpose of knowledge sharing and interoperation between programs
based on a shared conceptualisation, proposes a set of preliminary
_design criteria_ a formal ontology should follow:

* _Clarity_. An ontology should communicate the purpose and meaning of
defined terms. Definitions should be objective and independent of social
and computational context even if the underlying motivations arise from
them. Formalism is the means to this end, and when possible, the logical
formulation should be provided.

* _Coherence_. Ontology should permit inferences that are consistent
with the definitions. At the least, the defining axioms should be
logically consistent. Coherence should also apply to the concepts that
are defined informally, such as those described in natural language
documentation and examples.

* _Extensibility_. Ontology should be designed to anticipate the uses of
the shared vocabulary. It should offer a conceptual foundation for a
range of anticipated tasks and the representation should be crafted so
that one can extend and specialise the ontology monotonically. This
feature supports and encourages reuse and further specialisations of
ontologies and creation of the application profiles.

* _Minimal encoding bias_. The conceptualisation should be specified at
the knowledge level without depending on a particular symbol-level
encoding.

* _Minimal ontological commitment_. Ontology should require the minimal
ontological commitment sufficient to support the intended knowledge
sharing activities. Ontology should make as few claims as possible about
the world being modelled, allowing the parties committed to the ontology
freedom specialise and instantiate the ontology as needed. An
ontological commitment is an agreement to use the shared vocabulary,
with which queries and assertions are exchanged between agents, in a
coherent and consistent manner. We say that an agent commits to an
ontology if its behaviour is consistent with the definitions in the
ontology .

